title: Services
seoData: {}
blocks:
  - discriminant: heroWithBanner
    value:
      title: Commercial & Industrial <span class="text-secondary">Painting</span>
      subtitle: Professional Painting Contractor with Roots in Park City, Utah.
      bgImage: /images/services/blocks/0/value/bgImage.jpeg
      banner:
        title: Receive a FREE Estimate!
        button:
          label: Get a Free Estimate
          link: /
  - discriminant: sectionTitleDescription
    value:
      pretitle: Our Services
      title: Full Service Painting Contractor
      description: >
        Moorhouse Painting provides a wide range of painting services.&nbsp;
        Moorhouse offers custom interior and exterior painting services,
        allowing for a seamless installation experience.&nbsp; Moorhouse offers
        exceptional results in every home and commercial painting project.&nbsp;
        Thinking about refreshing the interior of your home’s walls, bedrooms or
        bathrooms?&nbsp; The Moorhouse Painting team approaches every painting
        project with an eye for detail and a complete painting plan.\

        \

        Finding the right team to paint your home or office can feel
        overwhelming, but with Moorhouse Coating and Painting you’ll have peace
        of mind and experts that treat your home with the respect it deserves.\
  - discriminant: twoColumn
    value:
      cardWithImage:
        - title: Exterior Residential Painting
          description: >-
            Painting the exterior of your house is about more than just curb
            appeal. The right paint provides a protective layer between your
            home and the elements, preventing costly damage to siding, trim and
            other materials. With proper prep work and the right paint for the
            job, you can expect your home’s paint job to look great and stand up
            to the conditions for several years.
          image: /images/services/blocks/2/value/cardWithImage/0/image.png
          Button:
            text: Learn more
            slug: exterior-house-painting-services
        - title: Interior Residential Painting
          description: "Moorhouse Coating specializes in providing exceptional interior painting as one of its many services. A new coat of paint can transform a room immediately.\_ There isn’t a single item in your home that will change the look and feel as dramatically as a fresh coat of paint.\nNo matter the scope of work involved, Moorhouse painters will transform any space with professionalism, cleanliness, and attention to detail in mind."
          image: /images/services/blocks/2/value/cardWithImage/1/image.png
          Button:
            text: Learn more
            slug: /
        - title: Commercial Painting
          description: >-
            Knowledgeable, professional and experienced, Moorhouse Coating
            provides superior commercial painting services at an affordable
            rate. We specialize in delivering quality painting that makes your
            business look great, while minimizing disruption to your normal
            operations.
          image: /images/services/blocks/2/value/cardWithImage/2/image.png
          Button:
            text: Learn more
            slug: /
        - title: Industrial Painting
          description: >-
            There are several important factors to consider when planning and
            completing an industrial painting project. These factors include
            substrate material, chemical exposure, atmospheric conditions, and
            required lifespan of the new coating system. Working with an
            experienced industrial painting contractor with many years of
            experience can be the difference in the success of a project.
          image: /images/services/blocks/2/value/cardWithImage/3/image.png
          Button:
            text: Learn more
            slug: /
  - discriminant: whatToExpect
    value:
      pretitle: Professional Commercial & Residential Painting
      heading: What To Expect When You Hire Moorhouse Coating
      cards:
        - cardIcon: /images/services/blocks/3/value/cards/0/cardIcon.svg
          cardText: Effective Communication Throughout The Process
          cardDescription: >-
            The Key to a successful project is found in good communication. As a
            licensed painting contractor, we have years of experience performing
            quality for commercial and residential clients.
        - cardIcon: /images/services/blocks/3/value/cards/1/cardIcon.svg
          cardText: We Value Integrity <br/> & Honesty
          cardDescription: >-
            To Paint with integrity we must be open and forthright, even when
            its difficult. Open, truthful conversations create opportunities for
            better analysis and future decisions.
        - cardIcon: /images/services/blocks/3/value/cards/2/cardIcon.svg
          cardText: Over 20+ Years <br/> Experience
          cardDescription: >-
            Our 20+ years experience in the painting, has shown us nearly every
            possible situation. Moorhouse handles your paint job in the most
            efficient, professional way possible.
        - cardIcon: /images/services/blocks/3/value/cards/3/cardIcon.svg
          cardText: Effective Communication Throughout The Process
          cardDescription: >-
            The Key to a successful project is found in good communication. As a
            licensed painting contractor, we have years of experience performing
            quality for commercial and residential clients.
        - cardIcon: /images/services/blocks/3/value/cards/4/cardIcon.svg
          cardText: We Value Integrity <br/> & Honesty
          cardDescription: >-
            To Paint with integrity we must be open and forthright, even when
            its difficult. Open, truthful conversations create opportunities for
            better analysis and future decisions.
        - cardIcon: /images/services/blocks/3/value/cards/5/cardIcon.svg
          cardText: Over 20+ Years <br/> Experience
          cardDescription: >-
            Our 20+ years experience in the painting, has shown us nearly every
            possible situation. Moorhouse handles your paint job in the most
            efficient, professional way possible.
  - discriminant: testimonials
    value:
      pretitle: Customer Testimonials
      heading: What People Say About Us
      testimonials:
        - rating: 5
          cardText: >-
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip
          authorName: Chris Michael
          authorpost: Park City
        - rating: 5
          cardText: >-
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip.
          authorName: Chris Michael
          authorpost: Park City
        - rating: 3
          cardText: >-
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip.
          authorName: Chris Michael
          authorpost: Park City
        - rating: 5
          cardText: >-
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip.
          authorName: Chris Michael
          authorpost: Park City
